// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    PhotoDetail: typeof import('./src/components/PhotoDetail.vue')['default']
    PhotoList: typeof import('./src/components/PhotoList.vue')['default']
    UiEmptyState: typeof import('./src/components/ui/UiEmptyState.vue')['default']
    UiErrorState: typeof import('./src/components/ui/UiErrorState.vue')['default']
    UiModal: typeof import('./src/components/ui/UiModal.vue')['default']
    UiPlaceholderBlock: typeof import('./src/components/ui/UiPlaceholderBlock.vue')['default']
    UiSearch: typeof import('./src/components/ui/UiSearch.vue')['default']
  }
}

export { }
